#!/usr/bin/env bash

VERSION=$(node -e 'console.log(require("./package.json").version)')
OWNER=rubeniskov
REPOSITORY=cuser
VERSION=$1

if [ -z "$VERSION" ]; then 
  echo >&2 "please specify the version by param, ex: $0 0.0.2"
  exit 1
fi

if [ -z "$GITHUB_ACCESS_TOKEN" ]; then 
  echo >&2 "missing env var GITHUB_ACCESS_TOKEN"
  exit 1
fi

lerna version --no-git-tag-version --repo-version $VERSION
node -e "var fs=require('fs').writeFileSync('./package.json', JSON.stringify(Object.assign(require('./package.json'), { version: '$VERSION' }), null, 2), 'utf8')"

git add package.json packages/*/package.json \
  && git commit -m "release: bump version $VERSION" \
  && git push origin $(git rev-parse --abbrev-ref HEAD) \
  && curl https://api.github.com/repos/$OWNER/$REPOSITORY/releases \
    --header "Authorization: token $GITHUB_ACCESS_TOKEN" \
    --data "{
        \"tag_name\": \"v$VERSION\",
        \"target_commitish\": \"master\",
        \"name\": \"v$VERSION\",
        \"body\": \"Release v$VERSION\",
        \"draft\": false,
        \"prerelease\": false
      }"
