const TYPE_ACTION_PREFIX = '@cuser';
const TYPE_ACTION_PROMISE_RESOLVED = `${TYPE_ACTION_PREFIX}/PROMISE_RESOLVED`;

const TYPE_ACTION_PUBLISH_MESSAGE = `${TYPE_ACTION_PREFIX}/PUBLISH_MESSAGE`;
const TYPE_ACTION_UPDATE_MESSAGE = `${TYPE_ACTION_PREFIX}/UPDATE_MESSAGE`;
const TYPE_ACTION_DELETE_MESSAGE = `${TYPE_ACTION_PREFIX}/DELETE_MESSAGE`;
const TYPE_ACTION_SEAL = `${TYPE_ACTION_PREFIX}/SEAL`;
const TYPE_ACTION_REHYDRATE = `${TYPE_ACTION_PREFIX}/REHYDRATE`;



module.exports = {
  TYPE_ACTION_PREFIX,
  TYPE_ACTION_PUBLISH_MESSAGE,
  TYPE_ACTION_PROMISE_RESOLVED,
  TYPE_ACTION_UPDATE_MESSAGE,
  TYPE_ACTION_DELETE_MESSAGE,
  TYPE_ACTION_SEAL,
  TYPE_ACTION_REHYDRATE
}
