name: npm-publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.14'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: ./node_modules/.bin/lerna publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
