name: release
on:
  release:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-20.04    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.14'
    - uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - run: yarn test
    - run: yarn coverage
  publish:
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - name: Set up Repository
      uses: actions/checkout@v2
    - name: NPM Publish 
      uses: docker://node:12.14
    - run: |
        yarn install
        echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
        yarn lerna publish from-package --yes --no-verify-access
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  docker:
    runs-on: ubuntu-20.04
    needs: publish
    steps:
    - name: Set up Repository
      uses: actions/checkout@v2
    - name: Set env
      run: echo "CUSER_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`|sed s/v//)" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          rubeniskov/cuser:latest
          rubeniskov/cuser:${{ env.CUSER_VERSION }}
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
        build-args: |
          version=${{ env.CUSER_VERSION }}
